version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_DATABASE=db_websays"
  web:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"
